<?php
function membrete_demo_puntos() {
    return array(
        array('accion' => 'Vista previa del documento', 'detalle' => 'Nuevo documento / Ver documento &rarr; Vista previa. Oficios, memorandos, circulares, acuerdos, resoluciones.', 'archivo' => 'VistaPrevia.php &rarr; plantillas/generar_documento.php', 'formato' => 'V', 'estado' => 'modulo', 'muestra' => 'oficio'),
        array('accion' => 'Firmar y Enviar', 'detalle' => 'Barra de acciones de la bandeja En elaboraci&oacute;n.', 'archivo' => 'include/tx/Tx.php &rarr; generar_documento.php', 'formato' => 'V', 'estado' => 'modulo', 'muestra' => 'memorando'),
        array('accion' => 'Forzar env&iacute;o manual / Reintentar env&iacute;o', 'detalle' => 'Acciones sobre documentos pendientes de env&iacute;o.', 'archivo' => 'include/tx/Tx.php &rarr; generar_documento.php', 'formato' => 'V', 'estado' => 'modulo', 'muestra' => 'oficio'),
        array('accion' => 'Descargar documento generado', 'detalle' => 'Pesta&ntilde;a Anexos / descarga del PDF del documento.', 'archivo' => 'anexos/anexos_descargar_archivo.php', 'formato' => 'V', 'estado' => 'modulo', 'muestra' => 'oficio'),
        array('accion' => 'Respaldo de documentos y migraci&oacute;n de bodega', 'detalle' => 'Regenera documentos que no est&aacute;n en bodega.', 'archivo' => 'backup/*, Administracion/migrar_bodega/*', 'formato' => 'V', 'estado' => 'modulo', 'muestra' => 'memorando'),
        array('accion' => 'Reporte de recorrido del documento', 'detalle' => 'Ver documento &rarr; Recorrido &rarr; PDF.', 'archivo' => 'reportes/generar_reporte_recorrido.php', 'formato' => 'R', 'estado' => 'modulo', 'muestra' => 'reporte'),
        array('accion' => 'Reporte de tareas', 'detalle' => 'Tareas &rarr; imprimir.', 'archivo' => 'reportes/generar_reporte_tareas.php', 'formato' => 'R', 'estado' => 'modulo', 'muestra' => 'reporte'),
        array('accion' => 'Traspaso de documentos f&iacute;sicos', 'detalle' => 'Comprobante de entrega f&iacute;sica.', 'archivo' => 'reportes/reporte_TraspasoDocFisico.php', 'formato' => 'R', 'estado' => 'modulo', 'muestra' => 'reporte'),
        array('accion' => 'Listado de &aacute;reas en PDF', 'detalle' => 'Administraci&oacute;n &rarr; &Aacute;reas &rarr; Lista.', 'archivo' => 'Administracion/dependencias/generarPDFAreas.php', 'formato' => 'R', 'estado' => 'modulo', 'muestra' => 'reporte'),
        array('accion' => 'Lista de expediente (carpeta virtual)', 'detalle' => 'Archivo / TRD &rarr; generar archivo.', 'archivo' => 'tipo_documental/lista_generar_archivo.php', 'formato' => 'R', 'estado' => 'modulo', 'muestra' => 'reporte'),
        array('accion' => 'B&uacute;squeda de documentos &rarr; Guardar como PDF', 'detalle' => 'Pantallas de b&uacute;squeda cl&aacute;sica y nueva.', 'archivo' => 'busqueda/, busquedaN/busqueda_generar_guardar_como.php', 'formato' => 'R', 'estado' => 'modulo', 'muestra' => 'reporte'),
        array('accion' => 'Reportes &rarr; Guardar como PDF', 'detalle' => 'M&oacute;dulo de reportes nuevo.', 'archivo' => 'reportes_new/reportes_generar_guardar_como.php', 'formato' => 'R', 'estado' => 'modulo', 'muestra' => 'reporte'),
        array('accion' => 'Reporte de instituciones', 'detalle' => 'Administraci&oacute;n &rarr; Instituciones.', 'archivo' => 'Administracion/tbasicas/reporte_instituciones.php', 'formato' => 'R', 'estado' => 'modulo', 'muestra' => 'reporte'),
        array('accion' => 'Reporte de usuarios', 'detalle' => 'Administraci&oacute;n &rarr; Usuarios (PDF y exportaci&oacute;n).', 'archivo' => 'Administracion/tbasicas/reporte_usuarios.php, Administracion/usuarios/reporte_usuarios_excel.php, reporte_usuarios_excel.php', 'formato' => 'R', 'estado' => 'modulo', 'muestra' => 'reporte'),
        array('accion' => 'B&uacute;squeda de usuarios &rarr; Guardar como PDF', 'detalle' => 'Administraci&oacute;n &rarr; Usuarios &rarr; b&uacute;squeda.', 'archivo' => 'Administracion/usuarios/busqueda_generar_usuario_guardar_como.php', 'formato' => 'R', 'estado' => 'modulo', 'muestra' => 'reporte'),
        array('accion' => 'Imprimir sobre', 'detalle' => 'Etiqueta postal del destinatario; nunca ha llevado membrete.', 'archivo' => 'plantillas/Sobres.php', 'formato' => 'S', 'estado' => 'sin', 'muestra' => ''),
        array('accion' => 'Comprobante de radicaci&oacute;n / c&oacute;digo de barras', 'detalle' => 'Etiquetas peque&ntilde;as; no aplica membrete.', 'archivo' => 'plantillas/CodigoBarras.php', 'formato' => 'B/C/T', 'estado' => 'sin', 'muestra' => ''),
        array('accion' => 'Validar plantilla (pantalla antigua de &Aacute;reas)', 'detalle' => 'Prueba el archivo cargado en Administraci&oacute;n de &Aacute;reas; se conserva como respaldo.', 'archivo' => 'Administracion/dependencias/validar_plantilla.php', 'formato' => 'V', 'estado' => 'legado', 'muestra' => ''),
    );
}
